name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: "3.x"
          check-latest: true
      - run: pip install --upgrade pip
      - run: pip install --upgrade -e ".[dev]"
      - run: pre-commit run --all-files
      - run: pyright
      - run: pytest -q -m "not live" --cov=rain_bypass --cov-fail-under=100
